### ISSUE TITLE
Problems running tests

### ISSUE THREAD

**Issue by Fplanas92** [denoptim-project/DENOPTIM#63]
Dear developers,

I have installed DENOPTIM under MacOS Big Sur, and the first test fails in the first molecule with error (from the log file)

denoptim.exception.DENOPTIMException: java.io.FileNotFoundException: /tmp/denoptim_test/t1/MOL000001_cs0.int_2 (No such file or directory)
  at denoptim.integration.tinker.TinkerUtils.readTinkerIC(TinkerUtils.java:274).

I have the Tinker directory well set, and I am using java and javac versions 1.8. Python and bash are also in the $PATH. This is all troubleshooting I did following the installation instructions, but I can't get it to work... Some help would be appreciated.

Best,
Ferran

**Comment by marco-foscato** [comment]
Dear @Fplanas92,
the error you are describing occurs usually as a result of a failed conversion of the results from a Tinker PSSROT calculation.  To confirm this, please, try to do the following: 

1.  Look at the content of folder /tmp/denoptim_test/t1/  You should find 21 files named "MOL000001_cs0.0XX" where XX goes from 00 to 20. Do you have them? If YES continue to step 2. If NO, then I need a deeper look at your files, so, please tell me what you have in there.
2. Try to use Tinker to convert "MOL000001_cs0.020", which is a Cartesian coordinate file, into an internal coordinate file. Here is the command you should try to run from inside /tmp/denoptim_test/t1/: 
`<yourPathToTinkersExecutables>/xyzint MOL000001_cs0.020 T` 
or, if Tinker is in your $PATH (as you indicated), just
`xyzint MOL000001_cs0.020 T` 

Note that this is exactly what DENOPTIM does in the step that generates the error message you have reported. 
Now, if the result of the above command is Tinker complaining with a message like the following:

     READXYZ  --  Check Connection of Atom     X to Atom     Y 
     TINKER is Unable to Continue; Terminating the Current Calculation

then, yes, good: The problem is that Tinker needs to be made capable of dealing with exotic connectivity matrices, like the ones that are indeed contained in DENOPTIM's test t1. Essentially, you need to extend the maximum allowed valence of any atom.
The solution to this problem is to set 'maxval=12' in the sizes.i file of Tinker's source code, and re-build Tinker. Note that 12 is just a number that fits well with these t1 tests that do include fancy molecules as they are meant to be stress tests. Increasing this number, however, increases the memory demands of Tinker, so you might not want to use such a large maxval for any Tinker job.

I hope this helps you. Let me know!

Marco

**Comment by Fplanas92** [comment]
Hi Marco,

Thanks for your answer. I obviously forgot to set the maxval to 12, hence the error. However, I am now having issues building Tinker from source. I will also post a ticket on their github, as this the errors I will describe below have nothing to do with DENOPTIM, but perhaps you know which is the issue.

When building Tinker I get this error:
ld: library not found for -lfftw3_threads

I have checked and in the /tinker/fftw/lib folder there is not a fftw3_threads library. There are only four files, which feels wrong.
cmake
libfftw3.a	
libfftw3.la
pkgconfig

The FFTW libraries were build with the following commands:
./configure --with-slow-timer --host=arm-macos-darwin --enable-single --enable-neon --prefix=/Applications/tinker/
make
make install

Many thanks,
Ferran

**Comment by marco-foscato** [comment]
Hi Ferran,

Since you are building the FFTW lib in a customized location (i.e., with --prefix to /Applications/tinker/), perhaps, the location of the FFTW library is not consistent with what declared in the makefile of Tinker (I guess something like /Applications/tinker/fftw). But this is really just a guess...

Good luck!

Marco

**Comment by Fplanas92** [comment]
Hi Marco,

Now I have a clean installation of FFTW and tinker. I changed the sizes.f file as indicated, but molecule 5 in test 1 is still failing.

When I run the test, each molecule takes longer time than before (which I see as an indirect evidence that the change in maxval is actually working), and molecules 1 to 4 work without a problem.
Molecule 5, however, fails with error.
/tmp/denoptim_test/t1/MOL000005_3Dbuilt.sdf not found!

The files produced for Molecule 5 in the temporary folder are:
-rw-r--r--  1 fplpa  wheel   804 Dec 20 23:41 /tmp/denoptim_test/t1/MOL000005_tinker.par
-rw-r--r--  1 fplpa  wheel  3376 Dec 20 23:42 /tmp/denoptim_test/t1/MOL000005_cs0.int
-rw-r--r--  1 fplpa  wheel   120 Dec 20 23:42 /tmp/denoptim_test/t1/MOL000005_cs0.key
-rw-r--r--  1 fplpa  wheel    74 Dec 20 23:42 /tmp/denoptim_test/t1/MOL000005_cs0.sub
-rw-r--r--  1 fplpa  wheel  1117 Dec 20 23:42 /tmp/denoptim_test/t1/MOL000005_cs0.log
-rw-r--r--  1 fplpa  wheel  5438 Dec 20 23:46 /tmp/denoptim_test/t1/MOL000005.log

And a look at _cs0.log indicates that:
 TORSIONS  --  Too many Torsional Angles; Increase MAXTORS

I do not remember reading any instructions recommending an increase of MAXTORS. I checked the torsions.f file and the value is set dynamically... Any suggestion?

Many thanks,
Ferran

**Comment by marco-foscato** [comment]
Hi Ferran,
yes, you are right, there is no indication about maxtors because its default value was large enough in older versions of Tinker (up to 6.3.3). So, it's very good that you have found out this limitation of newer versions. Thanks! 
Essentially, I see that versions 7.1.3 and 8.10.1 (latest) set maxtors=18*n, where n is the total number of atoms, while in old 6.3.3 sets maxtors = 6*maxatm with maxatm=10000. For MOL000005, which I thinks has 44 atoms in the Tinker job, maxtors would be limited to 18*44=792 in the latest versions of Tinker, but it would still be 60000 in version 6.3.3.

Anyway, as pointed out by the error message, Tinker must be made able to deal with more than the default number of torsions in order to model MOL000005 (i.e., a nido-carborane metal complex that is certainly well beyond the default type of chemistry that Tinker can be expected to deal with). The most straightforward solution I see, is to increase the factor used to calculate maxtors in torsions.f: from 18 to a value that is sufficiently large and that should be inferred by first making the format 10 line (i.e., the one that defines the error message "TORSIONS -- Too many Torsional Angles; Increase MAXTORS") in torsions.f write also the values of ntors and maxtors.

However, while these hacks are most likely going to successfully force Tinker to deal with the challenges of MOL000005, I think they are also most likely not really needed for the most common use cases. Therefore, since the other 4 molecules in t1 are successfully modelled, I would say that you can safely move on: the test is passed! That is, unless the chemistry you want to work with does in fact molecules as complex as the nido-carborane complex in MOL000005, in which case, yes, you'll have to tweak Tinker's latest version as explained above, or downgrade to version 6.3.3.

That said, your experience is very valuable. 

ACTIONS: The limitations of the newest versions of Tinker should be taken into account: I put this in out TODO list for the next release. Add test molecules that can work with default version of Tinker (i.e., without changing maxval), and make better error messages for when the molecules cannot be modelled by Tinker default version.

Marco

**Comment by Fplanas92** [comment]
Hi Marco,

Thanks for your answer. I won't be working with molecules of that complexity, so I will stick to the current settings and, in case I face further issues I will just downgrade to version 6.3.3 as you mentioned.

Best,
Ferran

**Comment by marco-foscato** [comment]
reopening this case just to make it wait for the changes addressing incompatibility between Tinker versions.
